const { app, BrowserWindow } = require('electron');
const path = require('path');
const { fork } = require('child_process');
const fs = require('fs');

// --- AUTOMATIC CONFIGURATION ---
// This file is generated by PortableAppKit.
// It automatically detects if a server exists in /server/index.js
// -------------------------------

const SERVER_ENTRY = path.join('server', 'index.js');
const SERVER_PORT = 3001; // Default port

let mainWindow;
let serverProcess;
const isDev = process.env.NODE_ENV === 'development';

function logToFile(message) {
    try {
        const logPath = path.join(app.getPath('desktop'), `app_debug.log`);
        const timestamp = new Date().toISOString();
        fs.appendFileSync(logPath, `[${timestamp}] ${message}\n`);
    } catch (e) { /* ignore */ }
}

function startServer() {
    const serverPath = isDev
        ? path.join(__dirname, '..', SERVER_ENTRY)
        : path.join(process.resourcesPath, SERVER_ENTRY);

    if (!fs.existsSync(serverPath) && !isDev) {
        console.log("No built-in server found, skipping.");
        return;
    }

    if (isDev && !fs.existsSync(path.join(__dirname, '..', SERVER_ENTRY))) {
        console.log("No server source found, skipping.");
        return;
    }

    logToFile(`Starting server: ${serverPath}`);

    // Pass system paths to server
    const env = {
        ...process.env,
        PORT: SERVER_PORT.toString(),
        ELECTRON_APP: 'true',
        USER_DATA_PATH: app.getPath('userData'),
        DOWNLOADS_PATH: app.getPath('downloads')
    };

    try {
        serverProcess = fork(serverPath, [], { env, silent: true });

        serverProcess.stdout.on('data', d => {
            console.log(`[Server] ${d}`);
            logToFile(`[Server] ${d}`);
        });
        serverProcess.stderr.on('data', d => {
            console.error(`[Server ERR] ${d}`);
            logToFile(`[Server ERR] ${d}`);
        });

    } catch (e) {
        logToFile(`Fatal Server Error: ${e.message}`);
    }
}

function stopServer() {
    if (serverProcess) {
        serverProcess.kill();
        serverProcess = null;
    }
}

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 1280,
        height: 800,
        webPreferences: {
            nodeIntegration: false,
            contextIsolation: true,
            preload: path.join(__dirname, 'preload.js')
        },
        autoHideMenuBar: true
    });

    // Wait for server?
    setTimeout(() => {
        if (isDev) {
            mainWindow.loadURL('http://localhost:3000');
        } else {
            // Try to find index.html in standard build folders
            const buildPath = path.join(__dirname, '..', 'build', 'index.html');
            const distPath = path.join(__dirname, '..', 'dist', 'index.html');

            let loadPath = buildPath;
            if (!fs.existsSync(buildPath) && fs.existsSync(distPath)) {
                loadPath = distPath;
            }

            mainWindow.loadFile(loadPath)
                .catch(e => logToFile(`Failed to load UI: ${e.message}`));
        }
    }, 2000);
}

app.on('ready', () => {
    startServer();
    createWindow();
});

app.on('window-all-closed', () => {
    stopServer();
    if (process.platform !== 'darwin') app.quit();
});

app.on('before-quit', stopServer);
