#!/usr/bin/env python3
"""
ION Kit - Project Initialization Wizard
Interactive setup for new projects
"""
import sys
import os
from pathlib import Path
import json

def get_input(prompt, default=None, options=None):
    """Get user input with validation"""
    if options:
        print(f"\n{prompt}")
        for i, option in enumerate(options, 1):
            print(f"  {i}. {option}")
        while True:
            choice = input(f"\nChoice (1-{len(options)})" + (f" [{default}]" if default else "") + ": ").strip()
            if not choice and default:
                return options[int(default) - 1]
            try:
                idx = int(choice) - 1
                if 0 <= idx < len(options):
                    return options[idx]
            except:
                pass
            print("Invalid choice, try again.")
    else:
        value = input(f"{prompt}" + (f" [{default}]" if default else "") + ": ").strip()
        return value if value else default

def create_project_structure(config):
    """Create project directories and files"""
    project_name = config['name']
    project_dir = Path(project_name)
    
    if project_dir.exists():
        print(f"\n[!] Directory '{project_name}' already exists!")
        overwrite = input("Overwrite? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("[X] Aborted")
            return False
    
    # Create directories
    directories = {
        'web': ['src', 'src/components', 'src/pages', 'src/styles', 'public', 'tests'],
        'api': ['src', 'src/routes', 'src/controllers', 'src/models', 'src/middleware', 'tests'],
        'mobile': ['src', 'src/screens', 'src/components', 'src/navigation', 'src/services', 'tests'],
        'fullstack': ['frontend/src', 'frontend/src/components', 'frontend/src/pages', 
                     'backend/src', 'backend/src/routes', 'backend/src/models', 'shared', 'tests']
    }
    
    project_type = config['type'].lower()
    dirs = directories.get(project_type, directories['web'])
    
    print(f"\n[SETUP] Creating project structure...")
    project_dir.mkdir(exist_ok=True)
    
    for dir_path in dirs:
        (project_dir / dir_path).mkdir(parents=True, exist_ok=True)
        print(f"  [OK] Created: {dir_path}/")
    
    return True

def generate_package_json(config):
    """Generate package.json based on project type"""
    project_dir = Path(config['name'])
    
    package = {
        "name": config['name'],
        "version": "1.0.0",
        "description": config.get('description', ''),
        "scripts": {},
        "dependencies": {},
        "devDependencies": {}
    }
    
    # Add scripts and dependencies based on framework
    if config['framework'] == 'Next.js':
        package['scripts'] = {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "lint": "next lint"
        }
        package['dependencies'] = {
            "next": "^14.0.0",
            "react": "^18.0.0",
            "react-dom": "^18.0.0"
        }
    elif config['framework'] == 'React':
        package['scripts'] = {
            "dev": "vite",
            "build": "vite build",
            "preview": "vite preview"
        }
        package['dependencies'] = {
            "react": "^18.0.0",
            "react-dom": "^18.0.0"
        }
        package['devDependencies'] = {
            "vite": "^5.0.0",
            "@vitejs/plugin-react": "^4.0.0"
        }
    elif config['framework'] == 'Express':
        package['scripts'] = {
            "dev": "nodemon src/index.js",
            "start": "node src/index.js"
        }
        package['dependencies'] = {
            "express": "^4.18.0"
        }
        package['devDependencies'] = {
            "nodemon": "^3.0.0"
        }
    
    # Write package.json
    package_path = project_dir / 'package.json'
    with open(package_path, 'w') as f:
        json.dump(package, f, indent=2)
    
    print(f"  [OK] Created: package.json")

def generate_readme(config):
    """Generate README.md"""
    project_dir = Path(config['name'])
    
    readme = f"""# {config['name']}

{config.get('description', 'A project built with ION Kit')}

## Technology Stack

- **Type:** {config['type']}
- **Framework:** {config['framework']}
- **Language:** {config.get('language', 'JavaScript')}

## Getting Started

### Installation
```bash
npm install
```

### Development
```bash
npm run dev
```

### Build
```bash
npm run build
```

## Project Structure

```
{config['name']}/
├── src/           # Source code
├── tests/         # Test files
└── package.json   # Dependencies
```

## Features

- Modern {config['framework']} setup
- Development server with hot reload
- Production-ready build configuration
- Test suite ready

## Generated by ION Kit v6.1.0

This project was initialized using the ION Kit project wizard.
"""
    
    readme_path = project_dir / 'README.md'
    with open(readme_path, 'w') as f:
        f.write(readme)
    
    print(f"  [OK] Created: README.md")

def generate_gitignore(config):
    """Generate .gitignore"""
    project_dir = Path(config['name'])
    
    gitignore = """# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Production
build/
dist/
.next/

# Environment
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*

# Misc
.cache/
"""
    
    gitignore_path = project_dir / '.gitignore'
    with open(gitignore_path, 'w') as f:
        f.write(gitignore)
    
    print(f"  [OK] Created: .gitignore")

def main():
    print("=" * 60)
    print("ION Kit - Project Initialization Wizard")
    print("=" * 60)
    
    # Gather project information
    config = {}
    
    config['name'] = get_input("\n[1/5] Project name")
    if not config['name']:
        print("[X] Project name is required")
        return
    
    config['type'] = get_input(
        "[2/5] Project type",
        default="1",
        options=['Web', 'API', 'Mobile', 'Fullstack']
    )
    
    # Framework based on type
    framework_options = {
        'Web': ['Next.js', 'React', 'Vue', 'Svelte'],
        'API': ['Express', 'Fastify', 'NestJS', 'FastAPI'],
        'Mobile': ['React Native', 'Flutter', 'Expo'],
        'Fullstack': ['Next.js', 'MERN', 'T3 Stack']
    }
    
    config['framework'] = get_input(
        "[3/5] Framework",
        default="1",
        options=framework_options.get(config['type'], ['React'])
    )
    
    config['language'] = get_input(
        "[4/5] Language",
        default="1",
        options=['TypeScript', 'JavaScript', 'Python']
    )
    
    config['description'] = get_input("[5/5] Project description (optional)")
    
    # Confirmation
    print("\n" + "=" * 60)
    print("Project Configuration:")
    print("=" * 60)
    for key, value in config.items():
        print(f"  {key.title()}: {value}")
    print("=" * 60)
    
    confirm = input("\nCreate project? (Y/n): ").strip().lower()
    if confirm and confirm != 'y':
        print("[X] Aborted")
        return
    
    # Create project
    if not create_project_structure(config):
        return
    
    if config['framework'] in ['Next.js', 'React', 'Express', 'Vue']:
        generate_package_json(config)
    
    generate_readme(config)
    generate_gitignore(config)
    
    print("\n" + "=" * 60)
    print("[OK] Project created successfully!")
    print("=" * 60)
    print(f"\nNext steps:")
    print(f"  cd {config['name']}")
    print(f"  npm install")
    print(f"  npm run dev")
    print(f"\nHappy coding! Generated by ION Kit v6.1.0")

if __name__ == "__main__":
    main()
